name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      - uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CURSEFORGE_ID: 1539899